### ISSUE TITLE
ntpdate in cron is kind of a bad practice

### ISSUE THREAD

**Issue by NicolasLM** [zenzire/ansible-bootstrap-ubuntu#4]
The admitted way to maintain a server's date is by using the ntp daemon, which deals with problems like clock drifting in a graceful manner.

``` yaml
- name: Install base programs
  apt: name={{item}} state=present
  with_items:
  - ntp

- name: Configure ntp
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp
```
